### ISSUE TITLE
Not appearing in add-ons after installing (Blender 2.90.1)

### ISSUE THREAD

**Issue by ecker00** [samytichadou/Auto_Reload_Blender_addon#10]
Going to `Preferences → Add-ons → Install...` and select the `__init__.py`, then in the console it says:
```
Modules Installed () from 'C:\\Users\\userName\\Downloads\\Auto_Reload-Blender_addon-1_3_1\\__init__.py' into 'C:\\Users\\userName\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons'
```
No errors, but the `Modules Installed ()` ← bracket is empty?

**Looking through the list of Add-ons, can't see `Auto Reload` listed anywhere, so can't enable it.**

**Comment by samytichadou** [comment]
can you try to rename the zip and its content root folder to remove special characters from it ? (like "-") and replace them by "_" Blender doesn't like that and sometimes does not see installed addons because of it.
You can also directly rename the folder where the zip was extracted (C:\\Users\\userName\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons)\\auto_reload...) and try !

**Comment by ecker00** [comment]
Checked and there were no spaces in the path. **But It worked to manually copy it to the add-ons folder like you suggested.** 👍 Very strange that the regular install approach didn't work.

**Comment by samytichadou** [comment]
yeah that's a special character isue, github generate some .zip with some upper dash (-) in the name, and this can be confusing for blender. If you remove it or change the name of installed folder, it often solves this issue ! 
Sorry for the inconvenience, i'll try to force github release without dash, but no idea of how to do it for now...
Cheers !
