### ISSUE TITLE
UDIM images aren't reloaded in Blender 3.3.0

### ISSUE THREAD

**Issue by Ogyly** [samytichadou/Auto_Reload_Blender_addon#22]
I tried to reload images using Auto Reload. Single Image file is reloaded but UDIM images aren't reloaded in Blender 3.3.0. Why?

this simple script can reload UDIM images, so your python doesn't read UDIM images?
```
import bpy

for image in bpy.data.images:
    image.reload()
```

**Comment by mohumohu-corp** [comment]
Hello.
The cause of this problem is that it is failing to get the file path, which for a UDIM image is formatted as, for example, "prefix<UDIM>.png". To get the file path for the tiles, you need to get the tile.label from the image.tiles collection property and compose the actual path using regular expression.

**Comment by Kapoff** [comment]
This is still a thing in 3.5 unfortunately.

**Comment by samytichadou** [comment]
new version supports udim and image sequences
