### ISSUE TITLE
Use checksum to fix same size files not reloading issue (bmp, psd)

### ISSUE THREAD

**Issue by ivxvm** [samytichadou/Auto_Reload_Blender_addon#38]
Blender 4.2.3 LTS, Windows 10.
BMP image doesn't autoreload.
Check timer freq: 1s
[+] Autoreload run
[+] Autoreload images

**Comment by samytichadou** [comment]
Hi sorry for delay, is the problem solved ?  
Auto reload checks exact file size to decide if reload is needed or not, would it be possible the file has not been modified (so no size change) ?

**Comment by ivxvm** [comment]
> Hi sorry for delay, is the problem solved ? Auto reload checks exact file size to decide if reload is needed or not, would it be possible the file has not been modified (so no size change) ?

No, problem is still there. I think in some formats file size doesn't change when you change the image. This is easy to imagine: changing 3 RGB bytes of pixel color to another 3 RGB bytes of pixel color don't change the total number of bytes. It's just that some formats like PNG are so tricky that changing the image and saving the file can potentially restructure the file, or modify some internal metadata, that's why file size change.

**Comment by samytichadou** [comment]
Thanks for the feedback, can you confirm the file size has *strictly* not changed in a situation where auto reload doesn't auto reload ?  
Checksum could work, agreed, but is less efficient than a simple file check.  
And an image format would not be the same size if changes have been made, because nowadays almost any image is compressed, even with *almost* no compression, and any changes triggers a different compression. I could be wrong, but i'm not sure that your issue comes from here.  
Any output in the console ? could you provide the two version of a file causing the problem ?  
Thanks.

**Comment by ivxvm** [comment]
> Thanks for the feedback, can you confirm the file size has _strictly_ not changed in a situation where auto reload doesn't auto reload ? Checksum could work, agreed, but is less efficient than a simple file check. And an image format would not be the same size if changes have been made, because nowadays almost any image is compressed, even with _almost_ no compression, and any changes triggers a different compression. I could be wrong, but i'm not sure that your issue comes from here. Any output in the console ? could you provide the two version of a file causing the problem ? Thanks.

This issue is specifically about BMP images. As I understand it, they're not compressed in most scenarios:

> https://en.wikipedia.org/wiki/BMP_file_format#Compression

> The [16bpp](https://en.wikipedia.org/wiki/Color_depth) and [32bpp](https://en.wikipedia.org/wiki/Color_depth) images are always stored uncompressed.

> Any output in the console ? could you provide the two version of a file causing the problem ?

I'm attaching an archive with 2 distinctly different BMP images with exactly the same size:

[TestImages.zip](https://github.com/user-attachments/files/18083420/TestImages.zip)

Here's how I tested the size:

```powershell
PS E:\Blender\Temp> (Get-Item -Path .\Test2.bmp).Length
12342
PS E:\Blender\Temp> (Get-Item -Path .\Test3.bmp).Length
12342
```

> Checksum could work, agreed, but is less efficient than a simple file check.

Maybe check only BMP using checksum and other images using existing method? For most formats, it's okay, it just doesn't work for BMP specifically. One of the reasons BMPs are useful is because they don't trigger extra dialogs on every save in Krita and allow to iterate on texture painting faster.

**Comment by samytichadou** [comment]
> This issue is specifically about BMP images. As I understand it, they're not compressed in most scenarios
Oh yeah you're right, totally forgot about bitmap images sorry ! 

I'll take a look on the checksum as a fallback, thanks for the catch and taking the time to check

**Comment by emittam** [comment]
Hello

I was having the same problem.
In my case, the psd file was not reloading when switching layers view.
Switching the layer view of a psd does not change the file size.

The psd files tend to be larger in file size, so it may take longer to calculate the checksum.
It used to use the file's file modification date and time (os.path.getmtime) to detect changes,
If you have a reason for the change to file size, we would appreciate it.

If there is no problem with os.path.getmtime, I would like to implement it and send a PullRequest.

I used DeepL to translate it since English is not my native language. If you have any questions about the confusion, please ask me.

Translated with DeepL.com (free version)

**Comment by moppius** [comment]
I came here because I was running into the same issue - a PNG with 0 compression, when resaved from Krita, is exactly the same size even if the content of the file has changed, so the auto-reload addon doesn't catch it.
I'm working around it for now by setting the PNG compression to 1 instead of 0 in Krita, but if I was using TGA, BMP etc. then the current size-only checking won't catch the image changes at all.

Maybe have an option in the addon preferences to choose between method of detection? Size (fastest), modtime (more accurate but maybe false positives as you say), checksum (slowest but most accurate).
That way people could choose what suits them best! 😎

**Comment by samytichadou** [comment]
https://github.com/samytichadou/Auto_Reload_Blender_addon/releases/tag/v3_1_1
(also available as direct update inside blender)

Should solve the problem, I fallbacked to modification time. As said, it can produce some false positive, but it is not a big problem and will not happen often.
And it is far more efficient than ckecksum, after conducted a few tests on .psd or .tiff files, the performance impact was to big to justify using this method.

I'm closing this, feel free to reopen if you encounter bugs with this. 
Thanks for your time and feedbacks !
